---
- name: "Gathering Dependency Facts"
  ansible.builtin.setup:
    filter:
      - 'env'
      - 'user_*'

- name: Making sure the install path exist
  ansible.builtin.file:
    path: "{{ dotfonts_install_dir }}"
    state: directory
    owner: "{{ ansible_facts['env']['USER'] }}"
    group: "{{ ansible_facts['user_gid'] }}"

- name: Downloading font file
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.file }}"
  loop: "{{ dotfonts_files }}"
  register: __download_stat
  notify: 
    - "Update Font Cache"

- name: "Extracting the font"
  ansible.builtin.unarchive:
    src: "{{ item.file }}"
    dest: "{{ dotfonts_install_dir }}"
    remote_src: true
  loop: "{{ dotfonts_files }}"
  when: item.extract|bool
  register: __extract_stat

- name: Removing trash files
  ansible.builtin.file:
    path: "{{ item.file }}"
    state: absent
    force: true
  loop: "{{ dotfonts_files }}"
  when: item.clean|bool
  register: __clean_stat
